

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware_security_headers }}
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    #HSTS
    stsIncludeSubdomains: true
    stsSeconds: 31536000
    # Remove the below headers by making them empty
    customResponseHeaders:
      X-Powered-By: ""
      X-Runtime: ""
      X-Version: ""
      X-AspNet-Version: ""
      X-Runtime-Microseconds: ""

