

apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: {{ .Release.Namespace }}

spec:
  minVersion: VersionTLS12
  sniStrict: {{ .Values.sniStrict }}
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
  {{ if .Values.clientAuth.secretNames }}
  clientAuth:
    # the CA certificate is extracted from key `tls.ca` of the given secrets.
    secretNames:
    {{- range .Values.clientAuth.secretNames }}
      - {{ . }}
    {{- end }}
    clientAuthType: VerifyClientCertIfGiven
  {{ end }}
