apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Release.Name }}-autoscaler"
spec:
  maxReplicas: {{ .Values.service.autoscale.maxReplicas }} # define max replica count
  minReplicas: {{ .Values.service.autoscale.minReplicas }}  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: {{ .Values.service.autoscale.cpuUtilization }}