spring:
  kafka:
    client-id: producer-groupId-1
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /bringdeinding
  port: 8081

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true