apiVersion: v1
kind: ConfigMap
metadata:
  name: mfs-config
data:
  db-database: storage
  kafka-bootstrap-servers: trackingeventns.servicebus.windows.net:9093
  kafka-group-id: groupId
  kafka-sasl-mechanism: PLAIN
  kafka-security-protocol: SASL_SSL
