apiVersion: v1
kind: ConfigMap
metadata:
  name: mfs-config
data:
  SPRING_DATA_MONGODB_DATABASE: storage
  SPRING_KAFKA_BOOTSTRAP-SERVERS: trackingeventns.servicebus.windows.net:9093
  SPRING_KAFKA_GROUP_ID: group-1
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: PLAIN
  SPRING_KAFKA_SECURITY_PROTOCOL: SASL_SSL
  SCHEMA_PATH: /schema/TrackingEventSchema.json
