
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Values.image.tag | default .Chart.AppVersion }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollingUpdate: {{ now | unixEpoch | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: "{{ .Values.service.contextPath }}/actuator/health/liveness"
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: "{{ .Values.service.contextPath }}/actuator/health/readiness"
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
          resources: # Define for autoscaling
            requests:
              cpu: {{ .Values.service.autoscale.minCpu }}
            limits:
              cpu: {{ .Values.service.autoscale.maxCpu }}
          volumeMounts:
            - name: schema-volume
              mountPath: /schema
#            - name: secret-volume
#              mountPath: /secret
          envFrom:
            - secretRef:
                name: mfs-secret
            - configMapRef:
                name: mfs-config
#          env:
#            # Secrets:
#            - name: SPRING_DATA_MONGODB_URI
#              valueFrom:
#                secretKeyRef:
#                  name: mfs-secret
#                  key: db-uri
#            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
#              valueFrom:
#                secretKeyRef:
#                  name: mfs-secret
#                  key: kafka-sasl-jaas-config
#            # Configs:
#            - name: SPRING_DATA_MONGODB_DATABASE
#              valueFrom:
#                configMapKeyRef:
#                  name: mfs-config
#                  key: db-database
#            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
#              valueFrom:
#                configMapKeyRef:
#                  name: mfs-config
#                  key: kafka-bootstrap-servers
#            - name: SPRING_KAFKA_GROUP_ID
#              valueFrom:
#                configMapKeyRef:
#                  name: mfs-config
#                  key: kafka-group-id
#            - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
#              valueFrom:
#                configMapKeyRef:
#                  name: mfs-config
#                  key: kafka-sasl-mechanism
#            - name: SPRING_KAFKA_SECURITY_PROTOCOL
#              valueFrom:
#                configMapKeyRef:
#                  name: mfs-config
#                  key: kafka-security-protocol
      volumes:
        - name: schema-volume
          configMap:
            name: json-schema
#        - name: secret-volume
#          secret:
#            secretName: mfs-secret