

replicaCount: 1

image:
  # the repository from where the image can be pulled
  repository: "trackingacr.azurecr.io"
  name: message-read-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083
  contextPath: /bringdeinding
