spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: storage
      uri: mongodb://rootuser:rootpass@localhost:27017/admin
  security:
    user:
      name: user
      password: password

server:
  port: 8080
  servlet:
    context-path: /mrs

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true