spring:
  kafka:
    bootstrap-servers: "localhost:29092"
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: storage
      port: 27017
      host: localhost
      auto-index-creation: true

server:
  servlet:
    context-path: /bringdeinding
  port: 8082

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true