spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    group.id: groupid
    properties:
      sasl:
        jaas:
          config: null
        mechanism: GSSAPI
    security:
      protocol: PLAINTEXT
  data:
    mongodb:
      database: storage
      uri: mongodb://localhost/
      authentication-database: admin
      auto-index-creation: true
  security:
    user:
      name: user
      password: password
schema:
  path: /Users/mheiden/Projects/sendungsverfolgung/MessageFilterService/schemas/TrackingEventSchema.json #classpath:TrackingEventSchema.json