spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    group.id: ${KAFKA_GROUP_ID}
    client-id: consumer-groupId-1
    properties:
      sasl.jaas.config: null #org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://nebrass.servicebus.windows.net/;SharedAccessKeyName=SendReceiveOnly;SharedAccessKey=XXXX";
      sasl.mechanism: GSSAPI #PLAIN
      security.protocol: PLAINTEXT #SASL_SSL

  data:
    mongodb:
      authentication-database: admin
      database: ${DB_DATABASE}
      uri: ${DB_URI}
      auto-index-creation: true

server:
  servlet:
    context-path: /bringdeinding
  port: 8082

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true