spring:
  kafka:
    client-id: consumer-groupId-1
    bootstrap-servers: localhost:29092
    group.id: groupid
    properties:
      sasl:
        jaas:
          config: null # Overwrite in k8s Secret
        mechanism: GSSAPI
    security:
      protocol: PLAINTEXT
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: storage
      uri: mongodb://rootuser:rootpass@localhost:27017/admin # Overwrite in k8s Secret
  security:
    user:
      name: user # Overwrite in k8s Secret
      password: password # Overwrite in k8s Secret

schema:
  path: ${SCHEMA_PATH}

server:
  port: 8080
  servlet:
    context-path: /mfs

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true