spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    group.id: ${KAFKA_GROUP_ID}
    client-id: consumer-groupId-1
    properties:
      sasl:
        jaas:
          config: ${KAFKA_SASL_JAAS_CONFIG}
        mechanism: ${KAFKA_SASL_MECHANISM}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL}

  data:
    mongodb:
      authentication-database: admin
      database: ${DB_DATABASE}
      uri: ${DB_URI}
      auto-index-creation: true

server:
  servlet:
    context-path: /bringdeinding
  port: 8082

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true