spring:
  kafka:
    client-id: consumer-groupId-1
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true

schema:
  path: ${SCHEMA_PATH}

server:
  servlet:
    context-path: /mfs

logging:
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: info, health, env, logfile, swagger-ui

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@

springfox:
  documentation:
    enabled: true